name: Robot Framework CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
 
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
 
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Inicializar Browser
        run: rfbrowser init
 
      - name: Ejecutar pruebas de API
        run: robot --outputdir resultados api
 
      - name: Ejecutar Suite de Regresión Completa
        run: robot --outputdir resultados api/07_regresion_completa.robot
 
      - name: Publicar resultados como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-robot-framework
          path: resultados/